[GLOBAL]

pants_version = "2.19.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.shell",
  "pants.backend.python.mixed_interpreter_constraints"
]


[python]
interpreter_constraints = ['>=3.10,<3.12']
